name: XCS224N
channels:
  - defaults
  - conda-forge
  - pytorch
dependencies:
  - python=3.8
  - numpy=1.23.5
  - scipy=1.9.3
  - scikit-learn=1.1.3
  - matplotlib=3.6.2
  - tqdm=4.64.1
  - docopt=0.6.2
  - notebook==6.5.2
  - pip=22.3.1
  - pip:
    - sentencepiece
    - sacrebleu
    - nltk
    - timeout_decorator
    - "--find-links https://download.pytorch.org/whl/torch_stable.html"
    - torch==1.13.1; sys_platform != "linux" and sys_platform != "win32"
    - torchvision==0.14.1; sys_platform != "linux" and sys_platform != "win32"
    - torch==1.13.1+cpu; sys_platform == "linux" or sys_platform == "win32"
    - torchvision==0.14.1+cpu; sys_platform == "linux" or sys_platform == "win32"